version: '2'

services:

  web:
    container_name: 'espiot-app'
    image: 'codenesium/espiot'
    build:
      context: .
      dockerfile: DockerFile
    environment:
       - ASPNETCORE_URLS=http://+:8000
       - ConnectionStrings__ApplicationDbContext=Host=espiot-db;Persist Security Info=False;User ID=postgres;Password=test;Database=espiot;
    volumes:
      - .:/var/www/app
    ports:
     - "8000:8000"
    depends_on:
     - "postgres"
    networks:
      - espiot-network

  postgres:
    container_name: 'espiot-db'
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: espiot
    networks:
      - espiot-network
    ports:
     - "5433:5432"
    restart: always

  watchtower:
    container_name: 'watchtower'
    image: v2tec/watchtower
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: --interval 30

volumes:
     pgdata:

networks:
    espiot-network:
       driver: bridge