language: csharp
mono: none
dotnet: 2.2
# ensure that docker is available on the travis machine
services:
  - docker
 
# ensure that the docker version is up to date so that we're sure that
# we can build any sort of docker-compose file that may be in the project
# e.g., the default ubuntu docker version can't build v3 compose files
sudo: required
before_deploy:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
 
# wire-up the script to build the application and deploy it to service fabric
# the script is run whenever a tag is added to the application's repository
deploy:
  - provider: script
    script: .travis/main.sh
    on:
      repo: codenesium/samples
      tags: true
script:
   -  dotnet build ESPIOT/ESPIOT.Api.Web/ESPIOT.Api.Web.csproj
   #-  dotnet build FileService/FileService.Api.Web/FileService.Api.Web.csproj
   #-  dotnet build Nebula/Nebula.Api.Web/Nebula.Api.Web.csproj
   #-  dotnet build Twitter/Twitter.Api.Web/Twitter.Api.Web.csproj
   #-  dotnet build PetShipping/PetShipping.Api.Web/PetShipping.Api.Web.csproj
   #-  dotnet build PetStore/PetStore.Api.Web/PetStore.Api.Web.csproj
   #-  dotnet build TicketingCRM/TicketingCRM.Api.Web/TicketingCRM.Api.Web.csproj
   #-  dotnet build StudioResourceManager/StudioResourceManager.Api.Web/StudioResourceManager.Api.Web.csproj
   #-  dotnet build StudioResourceManagerMT/StudioResourceManagerMT.Api.Web/StudioResourceManagerMT.Api.Web.csproj
   #-  dotnet build StackOverflow/StackOverflow.Api.Web/StackOverflow.Api.Web.csproj
   #-  dotnet build AdventureWorks/AdventureWorks.Api.Web/AdventureWorks.Api.Web.csproj
   
   #-  dotnet test ESPIOT/ESPIOT.Api.DataAccess.Tests/ESPIOT.Api.DataAccess.Tests.csproj
   #-  dotnet test FileService/FileService.Api.DataAccess.Tests/FileService.Api.DataAccess.Tests.csproj
   #-  dotnet test Nebula/Nebula.Api.DataAccess.Tests/Nebula.Api.DataAccess.Tests.csproj
   #-  dotnet test Twitter/Twitter.Api.DataAccess.Tests/Twitter.Api.DataAccess.Tests.csproj
   #-  dotnet test PetShipping/PetShipping.Api.DataAccess.Tests/PetShipping.Api.DataAccess.Tests.csproj
   #-  dotnet test PetStore/PetStore.Api.DataAccess.Tests/PetStore.Api.DataAccess.Tests.csproj
   #-  dotnet test TicketingCRM/TicketingCRM.Api.DataAccess.Tests/TicketingCRM.Api.DataAccess.Tests.csproj
   #-  dotnet test StudioResourceManager/StudioResourceManager.Api.DataAccess.Tests/StudioResourceManager.Api.DataAccess.Tests.csproj
   #-  dotnet test StudioResourceManagerMT/StudioResourceManagerMT.Api.DataAccess.Tests/StudioResourceManagerMT.Api.DataAccess.Tests.csproj
   #-  dotnet test StackOverflow/StackOverflow.Api.DataAccess.Tests/StackOverflow.Api.DataAccess.Tests.csproj
   #-  dotnet test AdventureWorks/AdventureWorks.Api.DataAccess.Tests/AdventureWorks.Api.DataAccess.Tests.csproj
   
   -  dotnet test ESPIOT/ESPIOT.Api.Services.Tests/ESPIOT.Api.Services.Tests.csproj
   #-  dotnet test FileService/FileService.Api.Services.Tests/FileService.Api.Services.Tests.csproj
   #-  dotnet test Nebula/Nebula.Api.Services.Tests/Nebula.Api.Services.Tests.csproj
   #-  dotnet test Twitter/Twitter.Api.Services.Tests/Twitter.Api.Services.Tests.csproj
   #-  dotnet test PetShipping/PetShipping.Api.Services.Tests/PetShipping.Api.Services.Tests.csproj
   #-  dotnet test PetStore/PetStore.Api.Services.Tests/PetStore.Api.Services.Tests.csproj
   #-  dotnet test TicketingCRM/TicketingCRM.Api.Services.Tests/TicketingCRM.Api.Services.Tests.csproj
   #-  dotnet test StudioResourceManager/StudioResourceManager.Api.Services.Tests/StudioResourceManager.Api.Services.Tests.csproj
   #-  dotnet test StudioResourceManagerMT/StudioResourceManagerMT.Api.Services.Tests/StudioResourceManagerMT.Api.Services.Tests.csproj
   #-  dotnet test StackOverflow/StackOverflow.Api.Services.Tests/StackOverflow.Api.Services.Tests.csproj
   #-  dotnet test AdventureWorks/AdventureWorks.Api.Services.Tests/AdventureWorks.Api.Services.Tests.csproj

   #-  dotnet test ESPIOT/ESPIOT.Api.Client.Tests/ESPIOT.Api.Client.Tests.csproj
   #-  dotnet test FileService/FileService.Api.Client.Tests/FileService.Api.Client.Tests.csproj
   #-  dotnet test Nebula/Nebula.Api.Client.Tests/Nebula.Api.Client.Tests.csproj
   #-  dotnet test Twitter/Twitter.Api.Client.Tests/Twitter.Api.Client.Tests.csproj
   #-  dotnet test PetShipping/PetShipping.Api.Client.Tests/PetShipping.Api.Client.Tests.csproj
   #-  dotnet test PetStore/PetStore.Api.Client.Tests/PetStore.Api.Client.Tests.csproj
   #-  dotnet test TicketingCRM/TicketingCRM.Api.Client.Tests/TicketingCRM.Api.Client.Tests.csproj
   #-  dotnet test StudioResourceManager/StudioResourceManager.Api.Client.Tests/StudioResourceManager.Api.Client.Tests.csproj
   #-  dotnet test StudioResourceManagerMT/StudioResourceManagerMT.Api.Client.Tests/StudioResourceManagerMT.Api.Client.Tests.csproj
   #-  dotnet test StackOverflow/StackOverflow.Api.Client.Tests/StackOverflow.Api.Client.Tests.csproj
   #-  dotnet test AdventureWorks/AdventureWorks.Api.Client.Tests/AdventureWorks.Api.Client.Tests.csproj
   
   #-  dotnet test ESPIOT/ESPIOT.Api.Web.Tests/ESPIOT.Api.Web.Tests.csproj
   #-  dotnet test FileService/FileService.Api.Web.Tests/FileService.Api.Web.Tests.csproj
   #-  dotnet test Nebula/Nebula.Api.Web.Tests/Nebula.Api.Web.Tests.csproj
   #-  dotnet test Twitter/Twitter.Api.Web.Tests/Twitter.Api.Web.Tests.csproj
   #-  dotnet test PetShipping/PetShipping.Api.Web.Tests/PetShipping.Api.Web.Tests.csproj
   #-  dotnet test PetStore/PetStore.Api.Web.Tests/PetStore.Api.Web.Tests.csproj
   #-  dotnet test TicketingCRM/TicketingCRM.Api.Web.Tests/TicketingCRM.Api.Web.Tests.csproj
   #-  dotnet test StudioResourceManager/StudioResourceManager.Api.Web.Tests/StudioResourceManager.Api.Web.Tests.csproj
   #-  dotnet test StudioResourceManagerMT/StudioResourceManagerMT.Api.Web.Tests/StudioResourceManagerMT.Api.Web.Tests.csproj
   #-  dotnet test StackOverflow/StackOverflow.Api.Web.Tests/StackOverflow.Api.Web.Tests.csproj
   #-  dotnet test AdventureWorks/AdventureWorks.Api.Web.Tests/AdventureWorks.Api.Web.Tests.csproj