import * as React from 'react';
import { Route, Switch, match, BrowserRouter } from 'react-router-dom';
import { App } from './app';
import Dashboard from './components/dashboard';
import { Security, ImplicitCallback, SecureRoute } from '@okta/okta-react';
import AWBuildVersionCreateComponent from './components/aWBuildVersion/aWBuildVersionCreateForm';
import AWBuildVersionDetailComponent from './components/aWBuildVersion/aWBuildVersionDetailForm';
import AWBuildVersionEditComponent from './components/aWBuildVersion/aWBuildVersionEditForm';
import AWBuildVersionSearchComponent from './components/aWBuildVersion/aWBuildVersionSearchForm';					
import DatabaseLogCreateComponent from './components/databaseLog/databaseLogCreateForm';
import DatabaseLogDetailComponent from './components/databaseLog/databaseLogDetailForm';
import DatabaseLogEditComponent from './components/databaseLog/databaseLogEditForm';
import DatabaseLogSearchComponent from './components/databaseLog/databaseLogSearchForm';					
import ErrorLogCreateComponent from './components/errorLog/errorLogCreateForm';
import ErrorLogDetailComponent from './components/errorLog/errorLogDetailForm';
import ErrorLogEditComponent from './components/errorLog/errorLogEditForm';
import ErrorLogSearchComponent from './components/errorLog/errorLogSearchForm';					
import DepartmentCreateComponent from './components/department/departmentCreateForm';
import DepartmentDetailComponent from './components/department/departmentDetailForm';
import DepartmentEditComponent from './components/department/departmentEditForm';
import DepartmentSearchComponent from './components/department/departmentSearchForm';					
import EmployeeCreateComponent from './components/employee/employeeCreateForm';
import EmployeeDetailComponent from './components/employee/employeeDetailForm';
import EmployeeEditComponent from './components/employee/employeeEditForm';
import EmployeeSearchComponent from './components/employee/employeeSearchForm';					
import JobCandidateCreateComponent from './components/jobCandidate/jobCandidateCreateForm';
import JobCandidateDetailComponent from './components/jobCandidate/jobCandidateDetailForm';
import JobCandidateEditComponent from './components/jobCandidate/jobCandidateEditForm';
import JobCandidateSearchComponent from './components/jobCandidate/jobCandidateSearchForm';					
import ShiftCreateComponent from './components/shift/shiftCreateForm';
import ShiftDetailComponent from './components/shift/shiftDetailForm';
import ShiftEditComponent from './components/shift/shiftEditForm';
import ShiftSearchComponent from './components/shift/shiftSearchForm';					
import AddressCreateComponent from './components/address/addressCreateForm';
import AddressDetailComponent from './components/address/addressDetailForm';
import AddressEditComponent from './components/address/addressEditForm';
import AddressSearchComponent from './components/address/addressSearchForm';					
import AddressTypeCreateComponent from './components/addressType/addressTypeCreateForm';
import AddressTypeDetailComponent from './components/addressType/addressTypeDetailForm';
import AddressTypeEditComponent from './components/addressType/addressTypeEditForm';
import AddressTypeSearchComponent from './components/addressType/addressTypeSearchForm';					
import BusinessEntityCreateComponent from './components/businessEntity/businessEntityCreateForm';
import BusinessEntityDetailComponent from './components/businessEntity/businessEntityDetailForm';
import BusinessEntityEditComponent from './components/businessEntity/businessEntityEditForm';
import BusinessEntitySearchComponent from './components/businessEntity/businessEntitySearchForm';					
import ContactTypeCreateComponent from './components/contactType/contactTypeCreateForm';
import ContactTypeDetailComponent from './components/contactType/contactTypeDetailForm';
import ContactTypeEditComponent from './components/contactType/contactTypeEditForm';
import ContactTypeSearchComponent from './components/contactType/contactTypeSearchForm';					
import CountryRegionCreateComponent from './components/countryRegion/countryRegionCreateForm';
import CountryRegionDetailComponent from './components/countryRegion/countryRegionDetailForm';
import CountryRegionEditComponent from './components/countryRegion/countryRegionEditForm';
import CountryRegionSearchComponent from './components/countryRegion/countryRegionSearchForm';					
import PasswordCreateComponent from './components/password/passwordCreateForm';
import PasswordDetailComponent from './components/password/passwordDetailForm';
import PasswordEditComponent from './components/password/passwordEditForm';
import PasswordSearchComponent from './components/password/passwordSearchForm';					
import PersonCreateComponent from './components/person/personCreateForm';
import PersonDetailComponent from './components/person/personDetailForm';
import PersonEditComponent from './components/person/personEditForm';
import PersonSearchComponent from './components/person/personSearchForm';					
import PhoneNumberTypeCreateComponent from './components/phoneNumberType/phoneNumberTypeCreateForm';
import PhoneNumberTypeDetailComponent from './components/phoneNumberType/phoneNumberTypeDetailForm';
import PhoneNumberTypeEditComponent from './components/phoneNumberType/phoneNumberTypeEditForm';
import PhoneNumberTypeSearchComponent from './components/phoneNumberType/phoneNumberTypeSearchForm';					
import StateProvinceCreateComponent from './components/stateProvince/stateProvinceCreateForm';
import StateProvinceDetailComponent from './components/stateProvince/stateProvinceDetailForm';
import StateProvinceEditComponent from './components/stateProvince/stateProvinceEditForm';
import StateProvinceSearchComponent from './components/stateProvince/stateProvinceSearchForm';					
import BillOfMaterialCreateComponent from './components/billOfMaterial/billOfMaterialCreateForm';
import BillOfMaterialDetailComponent from './components/billOfMaterial/billOfMaterialDetailForm';
import BillOfMaterialEditComponent from './components/billOfMaterial/billOfMaterialEditForm';
import BillOfMaterialSearchComponent from './components/billOfMaterial/billOfMaterialSearchForm';					
import CultureCreateComponent from './components/culture/cultureCreateForm';
import CultureDetailComponent from './components/culture/cultureDetailForm';
import CultureEditComponent from './components/culture/cultureEditForm';
import CultureSearchComponent from './components/culture/cultureSearchForm';					
import DocumentCreateComponent from './components/document/documentCreateForm';
import DocumentDetailComponent from './components/document/documentDetailForm';
import DocumentEditComponent from './components/document/documentEditForm';
import DocumentSearchComponent from './components/document/documentSearchForm';					
import IllustrationCreateComponent from './components/illustration/illustrationCreateForm';
import IllustrationDetailComponent from './components/illustration/illustrationDetailForm';
import IllustrationEditComponent from './components/illustration/illustrationEditForm';
import IllustrationSearchComponent from './components/illustration/illustrationSearchForm';					
import LocationCreateComponent from './components/location/locationCreateForm';
import LocationDetailComponent from './components/location/locationDetailForm';
import LocationEditComponent from './components/location/locationEditForm';
import LocationSearchComponent from './components/location/locationSearchForm';					
import ProductCreateComponent from './components/product/productCreateForm';
import ProductDetailComponent from './components/product/productDetailForm';
import ProductEditComponent from './components/product/productEditForm';
import ProductSearchComponent from './components/product/productSearchForm';					
import ProductCategoryCreateComponent from './components/productCategory/productCategoryCreateForm';
import ProductCategoryDetailComponent from './components/productCategory/productCategoryDetailForm';
import ProductCategoryEditComponent from './components/productCategory/productCategoryEditForm';
import ProductCategorySearchComponent from './components/productCategory/productCategorySearchForm';					
import ProductDescriptionCreateComponent from './components/productDescription/productDescriptionCreateForm';
import ProductDescriptionDetailComponent from './components/productDescription/productDescriptionDetailForm';
import ProductDescriptionEditComponent from './components/productDescription/productDescriptionEditForm';
import ProductDescriptionSearchComponent from './components/productDescription/productDescriptionSearchForm';					
import ProductModelCreateComponent from './components/productModel/productModelCreateForm';
import ProductModelDetailComponent from './components/productModel/productModelDetailForm';
import ProductModelEditComponent from './components/productModel/productModelEditForm';
import ProductModelSearchComponent from './components/productModel/productModelSearchForm';					
import ProductPhotoCreateComponent from './components/productPhoto/productPhotoCreateForm';
import ProductPhotoDetailComponent from './components/productPhoto/productPhotoDetailForm';
import ProductPhotoEditComponent from './components/productPhoto/productPhotoEditForm';
import ProductPhotoSearchComponent from './components/productPhoto/productPhotoSearchForm';					
import ProductReviewCreateComponent from './components/productReview/productReviewCreateForm';
import ProductReviewDetailComponent from './components/productReview/productReviewDetailForm';
import ProductReviewEditComponent from './components/productReview/productReviewEditForm';
import ProductReviewSearchComponent from './components/productReview/productReviewSearchForm';					
import ProductSubcategoryCreateComponent from './components/productSubcategory/productSubcategoryCreateForm';
import ProductSubcategoryDetailComponent from './components/productSubcategory/productSubcategoryDetailForm';
import ProductSubcategoryEditComponent from './components/productSubcategory/productSubcategoryEditForm';
import ProductSubcategorySearchComponent from './components/productSubcategory/productSubcategorySearchForm';					
import ScrapReasonCreateComponent from './components/scrapReason/scrapReasonCreateForm';
import ScrapReasonDetailComponent from './components/scrapReason/scrapReasonDetailForm';
import ScrapReasonEditComponent from './components/scrapReason/scrapReasonEditForm';
import ScrapReasonSearchComponent from './components/scrapReason/scrapReasonSearchForm';					
import TransactionHistoryCreateComponent from './components/transactionHistory/transactionHistoryCreateForm';
import TransactionHistoryDetailComponent from './components/transactionHistory/transactionHistoryDetailForm';
import TransactionHistoryEditComponent from './components/transactionHistory/transactionHistoryEditForm';
import TransactionHistorySearchComponent from './components/transactionHistory/transactionHistorySearchForm';					
import TransactionHistoryArchiveCreateComponent from './components/transactionHistoryArchive/transactionHistoryArchiveCreateForm';
import TransactionHistoryArchiveDetailComponent from './components/transactionHistoryArchive/transactionHistoryArchiveDetailForm';
import TransactionHistoryArchiveEditComponent from './components/transactionHistoryArchive/transactionHistoryArchiveEditForm';
import TransactionHistoryArchiveSearchComponent from './components/transactionHistoryArchive/transactionHistoryArchiveSearchForm';					
import UnitMeasureCreateComponent from './components/unitMeasure/unitMeasureCreateForm';
import UnitMeasureDetailComponent from './components/unitMeasure/unitMeasureDetailForm';
import UnitMeasureEditComponent from './components/unitMeasure/unitMeasureEditForm';
import UnitMeasureSearchComponent from './components/unitMeasure/unitMeasureSearchForm';					
import WorkOrderCreateComponent from './components/workOrder/workOrderCreateForm';
import WorkOrderDetailComponent from './components/workOrder/workOrderDetailForm';
import WorkOrderEditComponent from './components/workOrder/workOrderEditForm';
import WorkOrderSearchComponent from './components/workOrder/workOrderSearchForm';					
import PurchaseOrderHeaderCreateComponent from './components/purchaseOrderHeader/purchaseOrderHeaderCreateForm';
import PurchaseOrderHeaderDetailComponent from './components/purchaseOrderHeader/purchaseOrderHeaderDetailForm';
import PurchaseOrderHeaderEditComponent from './components/purchaseOrderHeader/purchaseOrderHeaderEditForm';
import PurchaseOrderHeaderSearchComponent from './components/purchaseOrderHeader/purchaseOrderHeaderSearchForm';					
import ShipMethodCreateComponent from './components/shipMethod/shipMethodCreateForm';
import ShipMethodDetailComponent from './components/shipMethod/shipMethodDetailForm';
import ShipMethodEditComponent from './components/shipMethod/shipMethodEditForm';
import ShipMethodSearchComponent from './components/shipMethod/shipMethodSearchForm';					
import VendorCreateComponent from './components/vendor/vendorCreateForm';
import VendorDetailComponent from './components/vendor/vendorDetailForm';
import VendorEditComponent from './components/vendor/vendorEditForm';
import VendorSearchComponent from './components/vendor/vendorSearchForm';					
import CreditCardCreateComponent from './components/creditCard/creditCardCreateForm';
import CreditCardDetailComponent from './components/creditCard/creditCardDetailForm';
import CreditCardEditComponent from './components/creditCard/creditCardEditForm';
import CreditCardSearchComponent from './components/creditCard/creditCardSearchForm';					
import CurrencyCreateComponent from './components/currency/currencyCreateForm';
import CurrencyDetailComponent from './components/currency/currencyDetailForm';
import CurrencyEditComponent from './components/currency/currencyEditForm';
import CurrencySearchComponent from './components/currency/currencySearchForm';					
import CurrencyRateCreateComponent from './components/currencyRate/currencyRateCreateForm';
import CurrencyRateDetailComponent from './components/currencyRate/currencyRateDetailForm';
import CurrencyRateEditComponent from './components/currencyRate/currencyRateEditForm';
import CurrencyRateSearchComponent from './components/currencyRate/currencyRateSearchForm';					
import CustomerCreateComponent from './components/customer/customerCreateForm';
import CustomerDetailComponent from './components/customer/customerDetailForm';
import CustomerEditComponent from './components/customer/customerEditForm';
import CustomerSearchComponent from './components/customer/customerSearchForm';					
import SalesOrderHeaderCreateComponent from './components/salesOrderHeader/salesOrderHeaderCreateForm';
import SalesOrderHeaderDetailComponent from './components/salesOrderHeader/salesOrderHeaderDetailForm';
import SalesOrderHeaderEditComponent from './components/salesOrderHeader/salesOrderHeaderEditForm';
import SalesOrderHeaderSearchComponent from './components/salesOrderHeader/salesOrderHeaderSearchForm';					
import SalesPersonCreateComponent from './components/salesPerson/salesPersonCreateForm';
import SalesPersonDetailComponent from './components/salesPerson/salesPersonDetailForm';
import SalesPersonEditComponent from './components/salesPerson/salesPersonEditForm';
import SalesPersonSearchComponent from './components/salesPerson/salesPersonSearchForm';					
import SalesReasonCreateComponent from './components/salesReason/salesReasonCreateForm';
import SalesReasonDetailComponent from './components/salesReason/salesReasonDetailForm';
import SalesReasonEditComponent from './components/salesReason/salesReasonEditForm';
import SalesReasonSearchComponent from './components/salesReason/salesReasonSearchForm';					
import SalesTaxRateCreateComponent from './components/salesTaxRate/salesTaxRateCreateForm';
import SalesTaxRateDetailComponent from './components/salesTaxRate/salesTaxRateDetailForm';
import SalesTaxRateEditComponent from './components/salesTaxRate/salesTaxRateEditForm';
import SalesTaxRateSearchComponent from './components/salesTaxRate/salesTaxRateSearchForm';					
import SalesTerritoryCreateComponent from './components/salesTerritory/salesTerritoryCreateForm';
import SalesTerritoryDetailComponent from './components/salesTerritory/salesTerritoryDetailForm';
import SalesTerritoryEditComponent from './components/salesTerritory/salesTerritoryEditForm';
import SalesTerritorySearchComponent from './components/salesTerritory/salesTerritorySearchForm';					
import ShoppingCartItemCreateComponent from './components/shoppingCartItem/shoppingCartItemCreateForm';
import ShoppingCartItemDetailComponent from './components/shoppingCartItem/shoppingCartItemDetailForm';
import ShoppingCartItemEditComponent from './components/shoppingCartItem/shoppingCartItemEditForm';
import ShoppingCartItemSearchComponent from './components/shoppingCartItem/shoppingCartItemSearchForm';					
import SpecialOfferCreateComponent from './components/specialOffer/specialOfferCreateForm';
import SpecialOfferDetailComponent from './components/specialOffer/specialOfferDetailForm';
import SpecialOfferEditComponent from './components/specialOffer/specialOfferEditForm';
import SpecialOfferSearchComponent from './components/specialOffer/specialOfferSearchForm';					
import StoreCreateComponent from './components/store/storeCreateForm';
import StoreDetailComponent from './components/store/storeDetailForm';
import StoreEditComponent from './components/store/storeEditForm';
import StoreSearchComponent from './components/store/storeSearchForm';					

const config = {
  oidc: {
    clientId: '<okta_client_id>',
    issuer: 'https://<okta_application_url>/oauth2/default',
    redirectUri: 'https://<your_public_webserver>/implicit/callback',
    scope: 'openid profile email',
  }
}

export const AppRouter: React.StatelessComponent<{}> = () => {
  const query = new URLSearchParams(location.search)

  return (
    <BrowserRouter>   
	<Security issuer={config.oidc.issuer}
        client_id={config.oidc.clientId}
        redirect_uri={config.oidc.redirectUri}>

      <div className="container-fluid">
        <Route component={App} />
	    <SecureRoute path="/protected" component={() => '<div>secure route</div>'} />
        <Switch>
          <Route exact path="/" component={Dashboard} />
		  					  <Route path="/awbuildversions/create" component={AWBuildVersionCreateComponent} />
					  <Route path="/awbuildversions/edit/:id" component={AWBuildVersionEditComponent} />
					  <Route path="/awbuildversions/:id" component={AWBuildVersionDetailComponent} />
					  <Route path="/awbuildversions" component={AWBuildVersionSearchComponent} />
										  <Route path="/databaselogs/create" component={DatabaseLogCreateComponent} />
					  <Route path="/databaselogs/edit/:id" component={DatabaseLogEditComponent} />
					  <Route path="/databaselogs/:id" component={DatabaseLogDetailComponent} />
					  <Route path="/databaselogs" component={DatabaseLogSearchComponent} />
										  <Route path="/errorlogs/create" component={ErrorLogCreateComponent} />
					  <Route path="/errorlogs/edit/:id" component={ErrorLogEditComponent} />
					  <Route path="/errorlogs/:id" component={ErrorLogDetailComponent} />
					  <Route path="/errorlogs" component={ErrorLogSearchComponent} />
										  <Route path="/departments/create" component={DepartmentCreateComponent} />
					  <Route path="/departments/edit/:id" component={DepartmentEditComponent} />
					  <Route path="/departments/:id" component={DepartmentDetailComponent} />
					  <Route path="/departments" component={DepartmentSearchComponent} />
										  <Route path="/employees/create" component={EmployeeCreateComponent} />
					  <Route path="/employees/edit/:id" component={EmployeeEditComponent} />
					  <Route path="/employees/:id" component={EmployeeDetailComponent} />
					  <Route path="/employees" component={EmployeeSearchComponent} />
										  <Route path="/jobcandidates/create" component={JobCandidateCreateComponent} />
					  <Route path="/jobcandidates/edit/:id" component={JobCandidateEditComponent} />
					  <Route path="/jobcandidates/:id" component={JobCandidateDetailComponent} />
					  <Route path="/jobcandidates" component={JobCandidateSearchComponent} />
										  <Route path="/shifts/create" component={ShiftCreateComponent} />
					  <Route path="/shifts/edit/:id" component={ShiftEditComponent} />
					  <Route path="/shifts/:id" component={ShiftDetailComponent} />
					  <Route path="/shifts" component={ShiftSearchComponent} />
										  <Route path="/addresses/create" component={AddressCreateComponent} />
					  <Route path="/addresses/edit/:id" component={AddressEditComponent} />
					  <Route path="/addresses/:id" component={AddressDetailComponent} />
					  <Route path="/addresses" component={AddressSearchComponent} />
										  <Route path="/addresstypes/create" component={AddressTypeCreateComponent} />
					  <Route path="/addresstypes/edit/:id" component={AddressTypeEditComponent} />
					  <Route path="/addresstypes/:id" component={AddressTypeDetailComponent} />
					  <Route path="/addresstypes" component={AddressTypeSearchComponent} />
										  <Route path="/businessentities/create" component={BusinessEntityCreateComponent} />
					  <Route path="/businessentities/edit/:id" component={BusinessEntityEditComponent} />
					  <Route path="/businessentities/:id" component={BusinessEntityDetailComponent} />
					  <Route path="/businessentities" component={BusinessEntitySearchComponent} />
										  <Route path="/contacttypes/create" component={ContactTypeCreateComponent} />
					  <Route path="/contacttypes/edit/:id" component={ContactTypeEditComponent} />
					  <Route path="/contacttypes/:id" component={ContactTypeDetailComponent} />
					  <Route path="/contacttypes" component={ContactTypeSearchComponent} />
										  <Route path="/countryregions/create" component={CountryRegionCreateComponent} />
					  <Route path="/countryregions/edit/:id" component={CountryRegionEditComponent} />
					  <Route path="/countryregions/:id" component={CountryRegionDetailComponent} />
					  <Route path="/countryregions" component={CountryRegionSearchComponent} />
										  <Route path="/passwords/create" component={PasswordCreateComponent} />
					  <Route path="/passwords/edit/:id" component={PasswordEditComponent} />
					  <Route path="/passwords/:id" component={PasswordDetailComponent} />
					  <Route path="/passwords" component={PasswordSearchComponent} />
										  <Route path="/people/create" component={PersonCreateComponent} />
					  <Route path="/people/edit/:id" component={PersonEditComponent} />
					  <Route path="/people/:id" component={PersonDetailComponent} />
					  <Route path="/people" component={PersonSearchComponent} />
										  <Route path="/phonenumbertypes/create" component={PhoneNumberTypeCreateComponent} />
					  <Route path="/phonenumbertypes/edit/:id" component={PhoneNumberTypeEditComponent} />
					  <Route path="/phonenumbertypes/:id" component={PhoneNumberTypeDetailComponent} />
					  <Route path="/phonenumbertypes" component={PhoneNumberTypeSearchComponent} />
										  <Route path="/stateprovinces/create" component={StateProvinceCreateComponent} />
					  <Route path="/stateprovinces/edit/:id" component={StateProvinceEditComponent} />
					  <Route path="/stateprovinces/:id" component={StateProvinceDetailComponent} />
					  <Route path="/stateprovinces" component={StateProvinceSearchComponent} />
										  <Route path="/billofmaterials/create" component={BillOfMaterialCreateComponent} />
					  <Route path="/billofmaterials/edit/:id" component={BillOfMaterialEditComponent} />
					  <Route path="/billofmaterials/:id" component={BillOfMaterialDetailComponent} />
					  <Route path="/billofmaterials" component={BillOfMaterialSearchComponent} />
										  <Route path="/cultures/create" component={CultureCreateComponent} />
					  <Route path="/cultures/edit/:id" component={CultureEditComponent} />
					  <Route path="/cultures/:id" component={CultureDetailComponent} />
					  <Route path="/cultures" component={CultureSearchComponent} />
										  <Route path="/documents/create" component={DocumentCreateComponent} />
					  <Route path="/documents/edit/:id" component={DocumentEditComponent} />
					  <Route path="/documents/:id" component={DocumentDetailComponent} />
					  <Route path="/documents" component={DocumentSearchComponent} />
										  <Route path="/illustrations/create" component={IllustrationCreateComponent} />
					  <Route path="/illustrations/edit/:id" component={IllustrationEditComponent} />
					  <Route path="/illustrations/:id" component={IllustrationDetailComponent} />
					  <Route path="/illustrations" component={IllustrationSearchComponent} />
										  <Route path="/locations/create" component={LocationCreateComponent} />
					  <Route path="/locations/edit/:id" component={LocationEditComponent} />
					  <Route path="/locations/:id" component={LocationDetailComponent} />
					  <Route path="/locations" component={LocationSearchComponent} />
										  <Route path="/products/create" component={ProductCreateComponent} />
					  <Route path="/products/edit/:id" component={ProductEditComponent} />
					  <Route path="/products/:id" component={ProductDetailComponent} />
					  <Route path="/products" component={ProductSearchComponent} />
										  <Route path="/productcategories/create" component={ProductCategoryCreateComponent} />
					  <Route path="/productcategories/edit/:id" component={ProductCategoryEditComponent} />
					  <Route path="/productcategories/:id" component={ProductCategoryDetailComponent} />
					  <Route path="/productcategories" component={ProductCategorySearchComponent} />
										  <Route path="/productdescriptions/create" component={ProductDescriptionCreateComponent} />
					  <Route path="/productdescriptions/edit/:id" component={ProductDescriptionEditComponent} />
					  <Route path="/productdescriptions/:id" component={ProductDescriptionDetailComponent} />
					  <Route path="/productdescriptions" component={ProductDescriptionSearchComponent} />
										  <Route path="/productmodels/create" component={ProductModelCreateComponent} />
					  <Route path="/productmodels/edit/:id" component={ProductModelEditComponent} />
					  <Route path="/productmodels/:id" component={ProductModelDetailComponent} />
					  <Route path="/productmodels" component={ProductModelSearchComponent} />
										  <Route path="/productphotoes/create" component={ProductPhotoCreateComponent} />
					  <Route path="/productphotoes/edit/:id" component={ProductPhotoEditComponent} />
					  <Route path="/productphotoes/:id" component={ProductPhotoDetailComponent} />
					  <Route path="/productphotoes" component={ProductPhotoSearchComponent} />
										  <Route path="/productreviews/create" component={ProductReviewCreateComponent} />
					  <Route path="/productreviews/edit/:id" component={ProductReviewEditComponent} />
					  <Route path="/productreviews/:id" component={ProductReviewDetailComponent} />
					  <Route path="/productreviews" component={ProductReviewSearchComponent} />
										  <Route path="/productsubcategories/create" component={ProductSubcategoryCreateComponent} />
					  <Route path="/productsubcategories/edit/:id" component={ProductSubcategoryEditComponent} />
					  <Route path="/productsubcategories/:id" component={ProductSubcategoryDetailComponent} />
					  <Route path="/productsubcategories" component={ProductSubcategorySearchComponent} />
										  <Route path="/scrapreasons/create" component={ScrapReasonCreateComponent} />
					  <Route path="/scrapreasons/edit/:id" component={ScrapReasonEditComponent} />
					  <Route path="/scrapreasons/:id" component={ScrapReasonDetailComponent} />
					  <Route path="/scrapreasons" component={ScrapReasonSearchComponent} />
										  <Route path="/transactionhistories/create" component={TransactionHistoryCreateComponent} />
					  <Route path="/transactionhistories/edit/:id" component={TransactionHistoryEditComponent} />
					  <Route path="/transactionhistories/:id" component={TransactionHistoryDetailComponent} />
					  <Route path="/transactionhistories" component={TransactionHistorySearchComponent} />
										  <Route path="/transactionhistoryarchives/create" component={TransactionHistoryArchiveCreateComponent} />
					  <Route path="/transactionhistoryarchives/edit/:id" component={TransactionHistoryArchiveEditComponent} />
					  <Route path="/transactionhistoryarchives/:id" component={TransactionHistoryArchiveDetailComponent} />
					  <Route path="/transactionhistoryarchives" component={TransactionHistoryArchiveSearchComponent} />
										  <Route path="/unitmeasures/create" component={UnitMeasureCreateComponent} />
					  <Route path="/unitmeasures/edit/:id" component={UnitMeasureEditComponent} />
					  <Route path="/unitmeasures/:id" component={UnitMeasureDetailComponent} />
					  <Route path="/unitmeasures" component={UnitMeasureSearchComponent} />
										  <Route path="/workorders/create" component={WorkOrderCreateComponent} />
					  <Route path="/workorders/edit/:id" component={WorkOrderEditComponent} />
					  <Route path="/workorders/:id" component={WorkOrderDetailComponent} />
					  <Route path="/workorders" component={WorkOrderSearchComponent} />
										  <Route path="/purchaseorderheaders/create" component={PurchaseOrderHeaderCreateComponent} />
					  <Route path="/purchaseorderheaders/edit/:id" component={PurchaseOrderHeaderEditComponent} />
					  <Route path="/purchaseorderheaders/:id" component={PurchaseOrderHeaderDetailComponent} />
					  <Route path="/purchaseorderheaders" component={PurchaseOrderHeaderSearchComponent} />
										  <Route path="/shipmethods/create" component={ShipMethodCreateComponent} />
					  <Route path="/shipmethods/edit/:id" component={ShipMethodEditComponent} />
					  <Route path="/shipmethods/:id" component={ShipMethodDetailComponent} />
					  <Route path="/shipmethods" component={ShipMethodSearchComponent} />
										  <Route path="/vendors/create" component={VendorCreateComponent} />
					  <Route path="/vendors/edit/:id" component={VendorEditComponent} />
					  <Route path="/vendors/:id" component={VendorDetailComponent} />
					  <Route path="/vendors" component={VendorSearchComponent} />
										  <Route path="/creditcards/create" component={CreditCardCreateComponent} />
					  <Route path="/creditcards/edit/:id" component={CreditCardEditComponent} />
					  <Route path="/creditcards/:id" component={CreditCardDetailComponent} />
					  <Route path="/creditcards" component={CreditCardSearchComponent} />
										  <Route path="/currencies/create" component={CurrencyCreateComponent} />
					  <Route path="/currencies/edit/:id" component={CurrencyEditComponent} />
					  <Route path="/currencies/:id" component={CurrencyDetailComponent} />
					  <Route path="/currencies" component={CurrencySearchComponent} />
										  <Route path="/currencyrates/create" component={CurrencyRateCreateComponent} />
					  <Route path="/currencyrates/edit/:id" component={CurrencyRateEditComponent} />
					  <Route path="/currencyrates/:id" component={CurrencyRateDetailComponent} />
					  <Route path="/currencyrates" component={CurrencyRateSearchComponent} />
										  <Route path="/customers/create" component={CustomerCreateComponent} />
					  <Route path="/customers/edit/:id" component={CustomerEditComponent} />
					  <Route path="/customers/:id" component={CustomerDetailComponent} />
					  <Route path="/customers" component={CustomerSearchComponent} />
										  <Route path="/salesorderheaders/create" component={SalesOrderHeaderCreateComponent} />
					  <Route path="/salesorderheaders/edit/:id" component={SalesOrderHeaderEditComponent} />
					  <Route path="/salesorderheaders/:id" component={SalesOrderHeaderDetailComponent} />
					  <Route path="/salesorderheaders" component={SalesOrderHeaderSearchComponent} />
										  <Route path="/salespersons/create" component={SalesPersonCreateComponent} />
					  <Route path="/salespersons/edit/:id" component={SalesPersonEditComponent} />
					  <Route path="/salespersons/:id" component={SalesPersonDetailComponent} />
					  <Route path="/salespersons" component={SalesPersonSearchComponent} />
										  <Route path="/salesreasons/create" component={SalesReasonCreateComponent} />
					  <Route path="/salesreasons/edit/:id" component={SalesReasonEditComponent} />
					  <Route path="/salesreasons/:id" component={SalesReasonDetailComponent} />
					  <Route path="/salesreasons" component={SalesReasonSearchComponent} />
										  <Route path="/salestaxrates/create" component={SalesTaxRateCreateComponent} />
					  <Route path="/salestaxrates/edit/:id" component={SalesTaxRateEditComponent} />
					  <Route path="/salestaxrates/:id" component={SalesTaxRateDetailComponent} />
					  <Route path="/salestaxrates" component={SalesTaxRateSearchComponent} />
										  <Route path="/salesterritories/create" component={SalesTerritoryCreateComponent} />
					  <Route path="/salesterritories/edit/:id" component={SalesTerritoryEditComponent} />
					  <Route path="/salesterritories/:id" component={SalesTerritoryDetailComponent} />
					  <Route path="/salesterritories" component={SalesTerritorySearchComponent} />
										  <Route path="/shoppingcartitems/create" component={ShoppingCartItemCreateComponent} />
					  <Route path="/shoppingcartitems/edit/:id" component={ShoppingCartItemEditComponent} />
					  <Route path="/shoppingcartitems/:id" component={ShoppingCartItemDetailComponent} />
					  <Route path="/shoppingcartitems" component={ShoppingCartItemSearchComponent} />
										  <Route path="/specialoffers/create" component={SpecialOfferCreateComponent} />
					  <Route path="/specialoffers/edit/:id" component={SpecialOfferEditComponent} />
					  <Route path="/specialoffers/:id" component={SpecialOfferDetailComponent} />
					  <Route path="/specialoffers" component={SpecialOfferSearchComponent} />
										  <Route path="/stores/create" component={StoreCreateComponent} />
					  <Route path="/stores/edit/:id" component={StoreEditComponent} />
					  <Route path="/stores/:id" component={StoreDetailComponent} />
					  <Route path="/stores" component={StoreSearchComponent} />
					        </Switch>
      </div>
	  </Security>
    </BrowserRouter>
  );
}

/*<Codenesium>
    <Hash>a6b43b70dc10c4a709ebcbe41518d92d</Hash>
</Codenesium>*/