USE [master]
GO
/****** Object:  Database [FileService]    Script Date: 3/12/2018 7:54:13 PM ******/
CREATE DATABASE [FileService]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FileService', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.PROD\MSSQL\DATA\FileService.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FileService_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.PROD\MSSQL\DATA\FileService_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [FileService] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FileService].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FileService] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FileService] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FileService] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FileService] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FileService] SET ARITHABORT OFF 
GO
ALTER DATABASE [FileService] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FileService] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FileService] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FileService] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FileService] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FileService] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FileService] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FileService] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FileService] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FileService] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FileService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FileService] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FileService] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FileService] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FileService] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FileService] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FileService] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FileService] SET RECOVERY FULL 
GO
ALTER DATABASE [FileService] SET  MULTI_USER 
GO
ALTER DATABASE [FileService] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FileService] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FileService] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FileService] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [FileService] SET DELAYED_DURABILITY = DISABLED 
GO
USE [FileService]
GO
/****** Object:  User [NebulaUser]    Script Date: 3/12/2018 7:54:14 PM ******/
CREATE USER [NebulaUser] FOR LOGIN [NebulaUser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [NebulaUser]
GO
/****** Object:  Table [dbo].[Bucket]    Script Date: 3/12/2018 7:54:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bucket](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](255) NOT NULL,
	[externalId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Bucket] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[File]    Script Date: 3/12/2018 7:54:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[File](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[externalId] [uniqueidentifier] NOT NULL,
	[privateKey] [varchar](64) NOT NULL,
	[publicKey] [varchar](64) NOT NULL,
	[location] [varchar](255) NOT NULL,
	[expiration] [datetime] NOT NULL,
	[extension] [varchar](32) NOT NULL,
	[dateCreated] [datetime] NOT NULL,
	[fileSizeInBytes] [decimal](18, 4) NOT NULL,
	[fileTypeId] [int] NOT NULL,
	[bucketId] [int] NULL,
	[description] [nvarchar](255) NULL,
 CONSTRAINT [PK_File] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[FileType]    Script Date: 3/12/2018 7:54:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FileType](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NOT NULL,
 CONSTRAINT [PK_FileType] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[VersionInfo]    Script Date: 3/12/2018 7:54:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VersionInfo](
	[Version] [bigint] NOT NULL,
	[AppliedOn] [datetime] NULL,
	[Description] [nvarchar](1024) NULL
) ON [PRIMARY]

GO
/****** Object:  Index [UC_Version]    Script Date: 3/12/2018 7:54:14 PM ******/
CREATE UNIQUE CLUSTERED INDEX [UC_Version] ON [dbo].[VersionInfo]
(
	[Version] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Bucket_externalId]    Script Date: 3/12/2018 7:54:14 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Bucket_externalId] ON [dbo].[Bucket]
(
	[externalId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_Bucket_name]    Script Date: 3/12/2018 7:54:14 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Bucket_name] ON [dbo].[Bucket]
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[File]  WITH CHECK ADD  CONSTRAINT [FK_File_Bucket] FOREIGN KEY([bucketId])
REFERENCES [dbo].[Bucket] ([id])
GO
ALTER TABLE [dbo].[File] CHECK CONSTRAINT [FK_File_Bucket]
GO
ALTER TABLE [dbo].[File]  WITH CHECK ADD  CONSTRAINT [FK_File_fileTypeId_FileType_id] FOREIGN KEY([fileTypeId])
REFERENCES [dbo].[FileType] ([id])
GO
ALTER TABLE [dbo].[File] CHECK CONSTRAINT [FK_File_fileTypeId_FileType_id]
GO
USE [master]
GO
ALTER DATABASE [FileService] SET  READ_WRITE 
GO
