version: '2'

services:

  web:
    container_name: 'fileservice-app'
    image: 'fileservice'
    build:
      context: .
      dockerfile: DockerFile
    environment:
       - ASPNETCORE_URLS=http://+:80
       - ConnectionStrings__ApplicationDbContext=Host=fileservice-db;Persist Security Info=False;User ID=postgres;Password=test;Database=fileservice;
       - DatabaseProvider=POSTGRESQL
       - MigrateDatabase=true
    volumes:
      - .:/var/www/app
    ports:
     - "80:80"
    depends_on:
     - "db"
    networks:
      - fileservice-network

  db:
    container_name: 'fileservice-db'
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: fileservice
    networks:
      - fileservice-network
    ports:
     - "5433:5432"
    restart: always

  watchtower:
    container_name: 'watchtower'
    image: v2tec/watchtower
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    networks:
      - fileservice-network
volumes:
     pgdata:

networks:
    fileservice-network:
       driver: bridge