version: '2'

services:

  app:
    container_name: 'petshipping-app'
    image: 'petshipping-app'
    build:
      context: .
      dockerfile: DockerFile
    environment:
       - ASPNETCORE_URLS=http://+:80
       - ConnectionStrings__ApplicationDbContext=Host=petshipping-db;Persist Security Info=False;User ID=postgres;Password=test;Database=petshipping;
       - DatabaseProvider=POSTGRESQL
       - MigrateDatabase=true
       - DebugSendAuthEmailsToClient=true
       - REACT_APP_API_URL=${REACT_APP_API_URL}
       - REACT_APP_HOST_SUBDIRECTORY=/
    volumes:
      - .:/var/www/app
    ports:
     - "80:80"
    depends_on:
     - "db"
    networks:
      - petshipping-network

  db:
    container_name: 'petshipping-db'
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: petshipping
    networks:
      - petshipping-network
    ports:
     - "5433:5432"
    restart: always

  watchtower:
    container_name: 'watchtower'
    image: v2tec/watchtower
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    networks:
      - petshipping-network
volumes:
     pgdata:

networks:
    petshipping-network:
       driver: bridge