version: '2'

services:

  web:
    container_name: 'petshipping-app'
    image: 'petshipping'
    build:
      context: .
      dockerfile: DockerFile
    environment:
       - ASPNETCORE_URLS=http://+:8000
       - ConnectionStrings__ApplicationDbContext=
    volumes:
      - .:/var/www/app
    ports:
     - "8000:8000"
    networks:
      - petshipping-network
    extra_hosts:
      - "localhost:10.0.2.2"
networks:
    petshipping-network:
       driver: bridge