version: '2'

services:
  app:
    container_name: 'studioresourcemanager-app'
    image: 'studioresourcemanager-app'
    build:
      context: .
      dockerfile: DockerFileReact
	  args
	  - REACT_APP_API_URL=http://192.168.99.100:81/
    environment:
       - REACT_APP_API_URL=http://192.168.99.100:81/
    volumes:
      - .:/var/www/app
    ports:
     - "80:80"
    networks:
      - studioresourcemanager-network

  api:
    container_name: 'studioresourcemanager-api'
    image: 'studioresourcemanager-api'
    build:
      context: .
      dockerfile: DockerFile
    environment:
       - ASPNETCORE_URLS=http://+:81
       - ConnectionStrings__ApplicationDbContext=Host=studioresourcemanager-db;Persist Security Info=False;User ID=postgres;Password=test;Database=studioresourcemanager;
       - DatabaseProvider=POSTGRESQL
       - MigrateDatabase=true
    volumes:
      - .:/var/www/api
    ports:
     - "81:81"
    depends_on:
     - "db"
    networks:
      - studioresourcemanager-network

  db:
    container_name: 'studioresourcemanager-db'
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: studioresourcemanager
    networks:
      - studioresourcemanager-network
    ports:
     - "5433:5432"
    restart: always

  watchtower:
    container_name: 'watchtower'
    image: v2tec/watchtower
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    networks:
      - studioresourcemanager-network
volumes:
     pgdata:

networks:
    studioresourcemanager-network:
       driver: bridge