version: '2'

services:

  web:
    container_name: 'studioresourcemanager-app'
    image: 'studioresourcemanager'
    build:
      context: .
      dockerfile: DockerFile
    environment:
       - ASPNETCORE_URLS=http://+:8000
       - ConnectionStrings__ApplicationDbContext=Host=studioresourcemanager-db;Persist Security Info=False;User ID=postgres;Password=test;Database=studioresourcemanager;
    volumes:
      - .:/var/www/app
    ports:
     - "8000:8000"
    depends_on:
     - "postgres"
    networks:
      - studioresourcemanager-network

  postgres:
    container_name: 'studioresourcemanager-db'
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: studioresourcemanager
    networks:
      - studioresourcemanager-network
    ports:
     - "5433:5432"
    restart: always

  watchtower:
    container_name: 'watchtower'
    image: v2tec/watchtower
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: --interval 30

volumes:
     pgdata:

networks:
    studioresourcemanager-network:
       driver: bridge