
# to run this with docker
# build a container named StackOverflow with 
# docker build -t StackOverflow .
# run with
# docker run -d -p 8000:8000  --add-host="localhost:10.0.2.2" --rm --name stackoverflowapp StackOverflow
# this will run your app exposed on the docker network and will forward port 8000 on the local machine to port 8000 in the container.
# On this machine it's http://192.168.99.100:8000 but it could be different for you.
# with the rm option the container will be deleted when it exits
# running this command will also expose your local network to the docker container so that localhost from
# inside the container will point to your local machine.
# see https://stackoverflow.com/questions/30495905/accessing-host-machine-as-localhost-from-a-docker-container-thats-also-inside-a for
# info about why 10.0.2.2 makes localhost accesible from the container.


FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app
EXPOSE 8000

# copy csproj and restore as distinct layers
COPY . ./

WORKDIR /app
RUN dotnet publish StackOverflow.Api.Web/StackOverflow.Api.Web.csproj -c Release  -o /app/out


FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "StackOverflow.Api.Web.dll"]
