version: '2'

services:
  app:
    container_name: 'twitter-app'
    image: 'twitter-app'
    build:
      context: .
      dockerfile: DockerFile
    environment:
       - ASPNETCORE_URLS=http://+:80
       - ConnectionStrings__ApplicationDbContext=Server=db;Persist Security Info=False;User ID=sa;Password=Passw0rd;Initial Catalog=twitter;MultipleActiveResultSets=True;Connection Timeout=10;
       - DatabaseProvider=MSSQL
       - MigrateDatabase=true
       - DebugSendAuthEmailsToClient=true
       - REACT_APP_API_URL=${REACT_APP_API_URL}
       - REACT_APP_HOST_SUBDIRECTORY=/
    volumes:
      - .:/var/www/app
    ports:
     - "80:80"
    networks:
      - twitter-network

  db:
    image: "microsoft/mssql-server-linux"
    container_name: 'db'
    environment:
       SA_PASSWORD: "Passw0rd"
       ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - twitter-network

  watchtower:
    container_name: 'watchtower'
    image: v2tec/watchtower
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    networks:
      - twitter-network

networks:
    twitter-network:
       driver: bridge